CREATE SEQUENCE SEQ_USER_LOGIN_LOG START 1;
CREATE TABLE USER_LOGIN_LOG
(
    LOG_ID          INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_USER_LOGIN_LOG'),
    USER_ID         INTEGER NOT NULL,
    LOGIN_TIMESTAMP TIMESTAMP,
    CONSTRAINT USER_ID_FK
        FOREIGN KEY (USER_ID)
            REFERENCES PLATFORM_USER (USER_ID)
            ON DELETE SET NULL
);

ALTER SEQUENCE SEQ_USER_LOGIN_LOG OWNED BY USER_LOGIN_LOG.LOG_ID;