CREATE SEQUENCE SEQ_POST START 1;
CREATE TABLE POST
(
    POST_ID         INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_POST'),
    TOPIC           VARCHAR NOT NULL,
    CONTENT         VARCHAR NOT NULL,
    CREATION_DATE   TIMESTAMP,
    UPDATE_DATE     TIMESTAMP,
    USER_ID         INTEGER
);

ALTER SEQUENCE SEQ_POST OWNED BY POST.POST_ID;

CREATE SEQUENCE SEQ_POST_COMMENT START 1;
CREATE TABLE POST_COMMENT
(
    COMMENT_ID      INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_POST_COMMENT'),
    CONTENT         VARCHAR NOT NULL,
    CREATION_DATE   TIMESTAMP,
    UPDATE_DATE     TIMESTAMP,
    POST_ID         INTEGER NOT NULL,
    USER_ID         INTEGER,
    CONSTRAINT POST_ID_FK
        FOREIGN KEY (POST_ID)
            REFERENCES POST (POST_ID)
                ON DELETE CASCADE
);

ALTER SEQUENCE SEQ_POST_COMMENT OWNED BY POST_COMMENT.COMMENT_ID;