CREATE SEQUENCE SEQ_POST_LIKE START 1;
CREATE TABLE POST_LIKE
(
    POST_LIKE_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_POST_LIKE'),
    POST_ID      INTEGER NOT NULL,
    USER_ID      INTEGER NOT NULL
);

ALTER SEQUENCE SEQ_POST_LIKE OWNED BY POST_LIKE.POST_LIKE_ID;