CREATE SEQUENCE SEQ_FRIEND START 1;
CREATE TABLE FRIEND
(
    FRIEND_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_FRIEND'),
    FIRST_USER_ID      INTEGER NOT NULL,
    SECOND_USER_ID      INTEGER NOT NULL
);

ALTER SEQUENCE SEQ_FRIEND OWNED BY FRIEND.FRIEND_ID;