CREATE SEQUENCE SEQ_ACHIEVEMENT START 1;
CREATE TABLE ACHIEVEMENT
(
    ACHIEVEMENT_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_ACHIEVEMENT'),
    NAME           VARCHAR NOT NULL,
    DESCRIPTION    VARCHAR NOT NULL
);

ALTER SEQUENCE SEQ_ACHIEVEMENT OWNED BY ACHIEVEMENT.ACHIEVEMENT_ID;


CREATE SEQUENCE SEQ_ACHIEVEMENT_USER START 1;
CREATE TABLE ACHIEVEMENT_USER
(
    ACHIEVEMENT_USER_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_ACHIEVEMENT_USER'),
    ACHIEVEMENT_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    CREATION_DATE TIMESTAMP
);

ALTER SEQUENCE SEQ_ACHIEVEMENT_USER OWNED BY ACHIEVEMENT_USER.ACHIEVEMENT_USER_ID