CREATE SEQUENCE SEQ_QUIZ START 1;
CREATE TABLE QUIZ
(
    QUIZ_ID        INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_QUIZ'),
    TITLE          VARCHAR(255),
    POINTS_TO_GAIN INTEGER,
    LESSON_ID      INTEGER
);

ALTER SEQUENCE SEQ_QUIZ OWNED BY QUIZ.QUIZ_ID;

CREATE SEQUENCE SEQ_PLATFORM_USER START 1;
CREATE TABLE PLATFORM_USER
(
    USER_ID       INTEGER      NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_PLATFORM_USER'),
    USERNAME      VARCHAR(255) NOT NULL,
    PASSWORD      VARCHAR(255) NOT NULL,
    NAME          VARCHAR,
    SURNAME       VARCHAR,
    EMAIL         VARCHAR,
    ROLE_ID       INTEGER,
    POINTS        INTEGER,
    ACTIVE        BOOL,
    AVATAR_URL    VARCHAR(255),
    CREATION_DATE TIMESTAMP
);

ALTER SEQUENCE SEQ_PLATFORM_USER OWNED BY PLATFORM_USER.USER_ID;

CREATE SEQUENCE SEQ_LESSON START 1;
CREATE TABLE LESSON
(
    LESSON_ID      INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_LESSON'),
    NAME           VARCHAR(255),
    LOGIN_REQUIRED BOOLEAN
);

ALTER SEQUENCE SEQ_LESSON OWNED BY LESSON.LESSON_ID;

CREATE SEQUENCE SEQ_LESSON_STAGE_COMPLETED START 1;
CREATE TABLE LESSON_STAGE_COMPLETED
(
    LESSON_STAGE_COMPLETED_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_LESSON_STAGE_COMPLETED'),
    LESSON_STAGE_ID           INTEGER NOT NULL,
    USER_ID                   INTEGER NOT NULL,
    COMPLETION_DATE           TIMESTAMP
);

ALTER SEQUENCE SEQ_LESSON_STAGE_COMPLETED OWNED BY LESSON_STAGE_COMPLETED.LESSON_STAGE_COMPLETED_ID;

CREATE SEQUENCE SEQ_LESSON_STAGE START 1;
CREATE TABLE LESSON_STAGE
(
    LESSON_STAGE_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_LESSON_STAGE'),
    LESSON_ID       INTEGER,
    NAME            VARCHAR(255),
    INDEX           NUMERIC(2, 1),
    CONSTRAINT LESSON_ID_FK
        FOREIGN KEY (LESSON_ID)
            REFERENCES LESSON (LESSON_ID)
            ON DELETE SET NULL
);

CREATE SEQUENCE SEQ_LESSON_STAGE_ELEMENT START 1;
CREATE TABLE LESSON_STAGE_ELEMENT
(
    LESSON_STAGE_ELEMENT_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_LESSON_STAGE_ELEMENT'),
    LESSON_STAGE_ID         INTEGER,
    VIDEO_URL               VARCHAR(2083),
    DESCRIPTION             VARCHAR(255),
    CONSTRAINT LESSON_STAGE_ID_FK
        FOREIGN KEY (LESSON_STAGE_ID)
            REFERENCES LESSON_STAGE (LESSON_STAGE_ID)
            ON DELETE CASCADE
);

ALTER SEQUENCE SEQ_LESSON_STAGE_ELEMENT OWNED BY LESSON_STAGE_ELEMENT.LESSON_STAGE_ELEMENT_ID;

CREATE SEQUENCE SEQ_QUIZ_QUESTION START 1;
CREATE TABLE QUIZ_QUESTION
(
    QUIZ_QUESTION_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_QUIZ_QUESTION'),
    QUIZ_ID          INTEGER,
    QUESTION_NUMBER  INTEGER,
    QUESTION_NAME    VARCHAR,
    POINTS           INTEGER,
    VIDEO_URL        VARCHAR(2083),
    CONSTRAINT QUIZ_ID_FK
        FOREIGN KEY (QUIZ_ID)
            REFERENCES QUIZ (QUIZ_ID)
            ON DELETE SET NULL
);

ALTER SEQUENCE SEQ_QUIZ_QUESTION OWNED BY QUIZ_QUESTION.QUIZ_QUESTION_ID;

CREATE SEQUENCE SEQ_QUIZ_ANSWER START 1;
CREATE TABLE QUIZ_ANSWER
(
    QUIZ_ANSWER_ID   INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_QUIZ_ANSWER'),
    QUIZ_QUESTION_ID INTEGER,
    DESCRIPTION      VARCHAR(255),
    CORRECT          BOOLEAN,
    CONSTRAINT QUIZ_QUESTION_ID_FK
        FOREIGN KEY (QUIZ_QUESTION_ID)
            REFERENCES QUIZ_QUESTION (QUIZ_QUESTION_ID)
            ON DELETE SET NULL
);

ALTER SEQUENCE SEQ_QUIZ_ANSWER OWNED BY QUIZ_ANSWER.QUIZ_ANSWER_ID;

CREATE SEQUENCE SEQ_QUIZ_COMPLETED START 1;
CREATE TABLE QUIZ_COMPLETED
(
    QUIZ_COMPLETED_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_QUIZ_COMPLETED'),
    USER_ID INTEGER NOT NULL,
    QUIZ_ID INTEGER NOT NULL,
    RESULT NUMERIC(4, 2),
    COMPLETION_DATE TIMESTAMP
);

ALTER SEQUENCE SEQ_QUIZ_COMPLETED OWNED BY QUIZ_COMPLETED.QUIZ_COMPLETED_ID;



