CREATE SEQUENCE SEQ_QUIZ START 1;
CREATE TABLE QUIZ
(
    QUIZ_ID        INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_QUIZ'),
    TITLE          VARCHAR(255),
    POINTS_TO_GAIN INTEGER
);

ALTER SEQUENCE SEQ_QUIZ OWNED BY QUIZ.QUIZ_ID;

CREATE SEQUENCE SEQ_PLATFORM_USER START 1;
CREATE TABLE PLATFORM_USER
(
    USER_ID       INTEGER      NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_PLATFORM_USER'),
    USERNAME      VARCHAR(255) NOT NULL,
    PASSWORD      VARCHAR(255) NOT NULL,
    NAME          VARCHAR,
    SURNAME       VARCHAR,
    EMAIL         VARCHAR,
    ROLE_ID       INTEGER,
    POINTS        INTEGER,
    ACTIVE        BOOL,
    AVATAR_URL    VARCHAR(255),
    CREATION_DATE TIMESTAMP
);

ALTER SEQUENCE SEQ_PLATFORM_USER OWNED BY PLATFORM_USER.USER_ID;

CREATE SEQUENCE SEQ_LESSON START 1;
CREATE TABLE LESSON
(
    LESSON_ID      INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_LESSON'),
    QUIZ_ID        INTEGER,
    NAME           VARCHAR(255),
    LOGIN_REQUIRED BOOLEAN,
    CONSTRAINT QUIZ_ID_FK
        FOREIGN KEY (QUIZ_ID)
            REFERENCES QUIZ (QUIZ_ID)
            ON DELETE SET NULL
);

ALTER SEQUENCE SEQ_LESSON OWNED BY LESSON.LESSON_ID;

CREATE SEQUENCE SEQ_LESSON_STAGE_COMPLETED START 1;
CREATE TABLE LESSON_STAGE_COMPLETED
(
    LESSON_STAGE_COMPLETED_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_LESSON_STAGE_COMPLETED'),
    LESSON_STAGE_ID           INTEGER NOT NULL,
    USER_ID                   INTEGER NOT NULL,
    COMPLETION_DATE           TIMESTAMP
);

ALTER SEQUENCE SEQ_LESSON_STAGE_COMPLETED OWNED BY LESSON_STAGE_COMPLETED.LESSON_STAGE_COMPLETED_ID;

CREATE SEQUENCE SEQ_LESSON_STAGE START 1;
CREATE TABLE LESSON_STAGE
(
    LESSON_STAGE_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_LESSON_STAGE'),
    LESSON_ID       INTEGER,
    NAME            VARCHAR(255),
    INDEX           NUMERIC(2, 1),
    CONSTRAINT LESSON_ID_FK
        FOREIGN KEY (LESSON_ID)
            REFERENCES LESSON (LESSON_ID)
            ON DELETE SET NULL
);

CREATE SEQUENCE SEQ_LESSON_STAGE_ELEMENT START 1;
CREATE TABLE LESSON_STAGE_ELEMENT
(
    LESSON_STAGE_ELEMENT_ID INTEGER NOT NULL PRIMARY KEY DEFAULT NEXTVAL('SEQ_LESSON_STAGE_ELEMENT'),
    LESSON_STAGE_ID         INTEGER,
    VIDEO_URL               VARCHAR(2083),
    DESCRIPTION             VARCHAR(255),
    CONSTRAINT LESSON_STAGE_ID_FK
        FOREIGN KEY (LESSON_STAGE_ID)
            REFERENCES LESSON_STAGE (LESSON_STAGE_ID)
            ON DELETE CASCADE
);

ALTER SEQUENCE SEQ_LESSON_STAGE_ELEMENT OWNED BY LESSON_STAGE_ELEMENT.LESSON_STAGE_ELEMENT_ID;
